server:
   port: 8383
spring:
   jpa:
      hibernate.ddl-auto: update
      show-sql: true
      generated-ddl: true
   datasource:
      url: jdbc:mysql://localhost:3306/venta
   username: root
   password: